### ISSUE TITLE
stop using `fakeProps` in tests and fix other warnings

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#142] opened 2018-04-24 12:26 UTC
Because jest will complain (a lot) about those:

```
    console.error node_modules/fbjs/lib/warning.js:33
      Warning: React does not recognize the `fakeProp` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fakeprop` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in div (created by WrapperComponent)
          in WrapperComponent
```

**Comment by andymikulski** [comment] 2018-04-24 14:59
Dupe of #89

**Closed by andymikulski** 2018-04-24 14:59 UTC
Labels: P5, fix
