### ISSUE TITLE
No tests for AuthButton component

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#221] opened 2018-06-20 21:18 UTC
Shouldn't be too hard to add one that renders with and without `userProfile` props.

**Comment by peterbe** [comment] 2018-06-21 21:09
let's wait for https://github.com/mozilla/delivery-console/pull/227

**Comment by rehandalal** [comment] 2018-07-05 12:03
Closing as dupe of #137

**Closed by rehandalal** 2018-07-05 12:03 UTC
Labels: P2, improvement
