### ISSUE TITLE
"Recipe cannot be created. The server failed to respond. Please try again. (JSON.parse: unexpected character at line 1 column 1 of the JSON data)" when trying to create a new opt-out recipe

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#938] opened 2019-06-20 14:36 UTC
**[Affected versions]:**
- Firefox Release 67.0.3, Build ID 20190618025334
- Firefox Beta 68.0b11, Build ID 20190617172838
- Firefox Nightly  69.0a1, Build ID 20190613215335

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net.
2. Click the new recipe button.
3. Select `opt-out-study` from the Action drop down.
4. Fill out all the fields with valid values.
5. Save the recipe and observe the behavior.

**[Expected results]:**
- The recipe is saved.

**[Actual results]:**
- The `Recipe cannot be created. The server failed to respond. Please try again. (JSON.parse: unexpected character at line 1 column 1 of the JSON data)` error message is displayed and the recipe is not saved.

**[Notes]:**
- The issue is not reproducible for other types of actions.
- The issue is also reproducible when trying to edit an already existing opt-out recipe.
- Attached a screen recording of the issue.
![error when trying to set-up optout recipe](https://user-images.githubusercontent.com/18304511/59857592-edba8900-9381-11e9-8149-c343e688a255.gif)

**Comment by SoftVision-CiprianMuresan** [comment] 2019-06-20 14:43
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”). 730:1:1
XHRPOSThttps://stage-admin.normandy.nonprod.cloudops.mozgcp.net/api/v3/recipe/
[HTTP/2.0 500 Internal Server Error 653ms]

POSThttps://delivery-console.stage.mozaws.net/__cspreport__
[HTTP/2.0 403 Forbidden 168ms]

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”). 730:1:1
POSThttps://delivery-console.stage.mozaws.net/__cspreport__
[HTTP/2.0 403 Forbidden 168ms]

Attempt to set a forbidden header was denied: Connection 1271259758-waffle_js_prod_core.js:570:146
XHRGEThttps://docs.google.com/spreadsheets/u/1/d/1WVrTobJMPIF5s5YO8UrtgB99R9MSwkpStCDz_quoEvA/bind?id=1WVrTobJMPIF5s5YO8UrtgB99R9MSwkpStCDz_quoEvA&sid=65ef8ea64546771&token=AC4w5VjBGariJotQvQ7ebRj-1XapJaisMw%3A1561040366342&includes_info_params=true&VER=8&lsq=1561021692399&u=07056766449456789743&vc=1&c=1&w=1&gsi=1&ssfi=1415&smv=65&cimpl=1&RID=rpc&SID=BD70AB203063A78&CI=0&AID=111&TYPE=xmlhttp&zx=4yj88oesuzx4&t=1

**Comment by mythmon** [comment] 2019-06-21 22:03
I was able to reproduce this. Since Normandy is sending back 500, there is definitely a Normandy bug here. There might also be a Delivery Console bug here, but I'm not sure.

I think this is related to this Normandy bug: https://github.com/mozilla/normandy/issues/1863. However I don't understand how we're triggering that, since the content being sent has all the right fields.

**Comment by jaredkerim** [comment] 2019-08-30 16:54
The permanent fix to this will be in https://github.com/mozilla/normandy/issues/1863 and other than better error handling there's nothing to be done in delivery console.

**Closed by jaredkerim** 2019-08-30 16:54 UTC
Labels: [QA]:Blocker issue
