### ISSUE TITLE
The uploaded extension cannot be removed by clicking the "x" button

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/delivery-console#857] opened 2019-03-21 12:58 UTC
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Versions]:**
- Firefox 66.0 and up

**[Prerequisites]:**
- Have access to the delivery console.

**[Steps to reproduce]:**
1. Navigate to http://delivery-console.stage.mozaws.net/.
2. Click the "Extensions" option.
3. Click the "+ New Extension" blue button.
4. Upload a .xpi file.
5. Hover the uploaded file and click the "x" button.
6. Observe the behavior.

**[Expected result]:**
- The uploaded file is removed.

**[Actual result]:**
- Nothing happens.

**[ Notes]:**
- Attached a screen recording with the issue:
![remove file button](https://user-images.githubusercontent.com/19226534/54753131-f7005200-4be8-11e9-9193-2ee906ca4928.gif)

**Comment by rehandalal** [comment] 2019-03-27 22:45
This is annoying UX but I believe the issue is related to how we populate the upload list. I believe fixing this would require rewriting how we write forms and would be quite a major change.

In light of the fact that we are planning on making extensions immutable and that you can simply choose another file by clicking the upload button when creating a new extension. I'm going to mark this as a `wontfix` for now.

**Closed** 2019-08-30 16:41 UTC
Labels: wontfix
