### ISSUE TITLE
Recipes are no longer displayed and the "Recipe cannot be created. The server failed to respond. ..." error message is displayed when trying to create a new recipe

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#1023] opened 2019-09-04 08:03 UTC
**[Affected versions]:**
- Firefox Beta 70.0b3, Build ID 20190902191027
- Firefox Nightly 71.0a1, Build ID 20190903215623

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net.
2. Observe the behavior.
3. Click the new recipe button.
4. Select any recipe type from the Action drop down.
5. Fill out all the fields with valid values.
6. Save the recipe and observe the behavior.

**[Expected results]:**
- Step 2: All recipes are displayed.
- Step 6: The recipe is saved.

**[Actual results]:**
- Step 2: `No Data` message is displayed.
- Step 6: The `Recipe cannot be created. The server failed to respond. Please try again. (JSON.parse: unexpected character at line 1 column 1 of the JSON data)` error message is displayed and the recipe is not saved.

**[Notes]:**
- The issue is not reproducible for extensions or when trying to upload new extensions.
- When navigating directly to a previously set-up recipe, no data is displayed.
- See also #938.
- Exported the Network tab as har: [link](https://drive.google.com/open?id=19Rw81cYV8gNRfBFrMbkTEPnfTjsXWxKY)
- Attached a screen recording of the issue.
![recipes not displayed and can no longer be created](https://user-images.githubusercontent.com/18304511/64236353-e4fa3d80-cf02-11e9-8de6-7c96bb09b32d.gif)

**Comment by mythmon** [comment] 2019-09-04 22:01
Version `v1.124.0` of Normandy had a bad migration that caused the site to be unusable last night when it was deployed to stage. Normandy stage has been rolled back to `v123`. With that roll back, this immediate problem should be fixed, and we're tracking the full solution in mozilla/normandy#1971.

In general, errors like "The server failed to respond. Please try again. (JSON.parse: unexpected character at line 1 column 1 of the JSON data)", usually  indicate that there was a server error, and so the problem is with [Normandy](https://github.com/mozilla/normandy/issues), not Delivery console.

**Closed by mythmon** 2019-09-04 22:01 UTC
Labels: [QA]:Blocker issue
